name: "Issue Labeler"
description: "trigger an action based on issue comment"
inputs:
  github-token:
    description: "Github token"
    required: true
    required: true
  assignees:
    description: "assignees to be assigned when keyword is found"


outputs:
runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: alert-circle
  color: gray-dark
